---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: acm-policies-openshift-gitops

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/name: acm-policies-openshift-gitops
    app.kubernetes.io/component: governance
    app.kubernetes.io/part-of: platform-management

resources:
- ManagedClusterSetBinding_default.yaml

generators:
- PolicyGenerator_cluster-management.yaml
# TODO: Temporarily disable as this is broken, troubleshooting in-progress.
# - PolicyGenerator_tenant-management.yaml
