approveManualInstallPlanViaHook: true

installPlanApproverAndVerifyJobsImage: quay.io/openshift/origin-cli:4.15

operatorGroups:
- name: external-secrets-operator-1
  createNamespace: true
  targetOwnNamespace: false
  otherTargetNamespaces:

operators:
- channel: stable
  installPlanApproval: Manual
  name: external-secrets-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
  csv: external-secrets-operator.v0.8.1
  namespace: external-secrets-operator-1
  installPlanVerifierActiveDeadlineSeconds: 1200
commonLabels:
  test-label: xyz123
