approveManualInstallPlanViaHook: false

installPlanApproverAndVerifyJobsImage: quay.io/openshift/origin-cli:4.15

operatorGroups:
  cmo:
    name: costmanagement-metrics-operator
    createNamespace: true
    targetOwnNamespace: false
    otherTargetNamespaces:

operators:
  cmo:
    name: costmanagement-metrics-operator
    channel: stable
    csv: costmanagement-metrics-operator.2.0.0
    installPlanApproval: Manual
    source: operatorhubio-catalog
    sourceNamespace: olm
    namespace: costmanagement-metrics-operator
    installPlanVerifierActiveDeadlineSeconds: 1200
