---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.tenantName }}-workload-root
  namespace: '{{ $.Values.tenantGitOpsNamespace }}'
spec:
  project: '{{ $.Values.tenantName }}'
  source:
    repoURL: '{{ $.Values.tenantWorkloads.gitRepo }}'
    path: '{{ $.Values.tenantWorkloads.path}}'
    targetRevision: '{{ $.Values.tenantWorkloads.gitRevision}}'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: '{{ $.Values.tenantGitOpsNamespace }}'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: -1
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 10m
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: {{ $.Values.tenantGitOpsNamespace }}
