approveManualInstallPlanViaHook: true

installPlanApproverAndVerifyJobsImage: quay.io/openshift/origin-cli:4.15

operatorGroups:
- name: external-secrets-operator-3
  createNamespace: true
  targetOwnNamespace: false
  otherTargetNamespaces:
- name: argocd-operator
  createNamespace: true
  targetOwnNamespace: true
  otherTargetNamespaces:

operators:
- name: external-secrets-operator
  channel: stable
  csv: external-secrets-operator.v0.8.1
  installPlanApproval: Manual
  source: operatorhubio-catalog
  sourceNamespace: olm
  namespace: external-secrets-operator-3
  installPlanVerifierActiveDeadlineSeconds: 1200
- name: argocd-operator
  channel: alpha
  csv: argocd-operator.v0.6.0
  installPlanApproval: Manual
  source: operatorhubio-catalog
  sourceNamespace: olm
  namespace: argocd-operator
  installPlanVerifierActiveDeadlineSeconds: 1200
commonLabels:
  test-label: xyz123
