---
apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  name: gatekeeper
spec:
  audit:
    auditChunkSize: 500
    logLevel: INFO
    replicas: 1
    auditEventsInvolvedNamespace: Enabled
    emitAuditEvents: Enabled
  validatingWebhook: Enabled
  mutatingWebhook: Disabled
  webhook:
    emitAdmissionEvents: Enabled
    logLevel: INFO
    replicas: 2
    logMutations: Enabled
    admissionEventsInvolvedNamespace: Enabled
