---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets-operator

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/name: external-secrets-operator
    app.kubernetes.io/component: secrets-management
    app.kubernetes.io/part-of: platform-management

# NOTE: setting chart home as a workaround for https://github.com/argoproj/argo-cd/issues/8008
helmGlobals:
  chartHome: charts/external-secrets-operator
helmCharts:
- name: operators-installer
  repo: https://redhat-cop.github.io/helm-charts
  version: 3.0.1
  valuesFile: values.yaml
