---
operatorGroups:
- name: external-secrets-operator
  createNamespace: false # Let Argo Application create it so it can give itself namespace admin
  targetOwnNamespace: false
operators:
- channel: stable
  installPlanApproval: Manual
  automaticIntermediateManualUpgrades: true
  name: external-secrets-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  csv: external-secrets-operator.v0.10.3
  namespace: external-secrets-operator
