---
operatorGroups:
- name: openshift-gitops-operator
  createNamespace: true
  targetOwnNamespace: false
operators:
- channel: latest
  installPlanApproval: Manual
  automaticIntermediateManualUpgrades: true
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  csv: openshift-gitops-operator.v1.13.1
  namespace: openshift-gitops-operator
