---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 00-cluster-management-root
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: 00-cluster-management-root
    app.kubernetes.io/component: cluster-management
    app.kubernetes.io/part-of: platform-management
spec:
  project: cluster-management
  source:
    # TODO
    # 1) hub (cluster) -> openshift-gitops-policies (namespace) -> {MANAGED_CLUSTER_NAME}-cluster-gitops-repo-config (ConfigMap)
    # 2) managed cluster (cluster) -> openshift-gitops (namespace) -> cluster-gitops-repo-config (ConfigMap)
    # 3) error
    repoURL: '{{ default (default ("ERROR: looking up repo url") (lookup "v1" "ConfigMap" "openshift-gitops" "cluster-gitops-repo-config").data.gitopsRepository) ("{{hub default ("") (lookup "v1" "ConfigMap" "openshift-gitops-policies" (printf "%s-cluster-gitops-repo-config" .ManagedClusterName)).data.gitopsRepository hub}}") }}'
    targetRevision: '{{ default (default ("ERROR: looking up repo revision") (lookup "v1" "ConfigMap" "openshift-gitops" "cluster-gitops-repo-config").data.gitopsRevision) ("{{hub default ("") (lookup "v1" "ConfigMap" "openshift-gitops-policies" (printf "%s-cluster-gitops-repo-config" .ManagedClusterName)).data.gitopsRevision hub}}") }}'
    path: 'clusters/{{ default (default (fromClusterClaim "name") (lookup "v1" "ConfigMap" "openshift-gitops" "cluster-gitops-repo-config").data.gitopsCluster) ("{{hub default ("") (lookup "v1" "ConfigMap" "openshift-gitops-policies" (printf "%s-cluster-gitops-repo-config" .ManagedClusterName)).data.gitopsCluster hub}}") }}'

  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

    # since there are inter-dependencies between applications that can take a while to sort themselves out allow for infinite retries
    retry:
      limit: -1
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 10m

    # ensure Argo gets namespace admin on created namespace
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
