---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-management
spec:
  description: Applications that manage the cluster
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
