---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenant-management
spec:
  description: Applications that manage tenants of the cluster
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
