---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crd-admin
rules:
- verbs:
  - "*"
  apiGroups:
  - apiextensions.k8s.io
  resources:
  - 'customresourcedefinitions'
  