---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-admin
rules:
- verbs:
  - "*"
  apiGroups:
  - argoproj.io
  resources:
  - appprojects
  - applications
  - argocds
